# Generated by Django 4.1.4 on 2022-12-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.aluno"
            ),
        ),
    ]
