# Generated by Django 4.1.4 on 2022-12-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_performance_aluno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treino",
            name="plano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.plano"
            ),
        ),
    ]
